const jargonMap: Record<string, string> = {
    "utilize": "use",
    "utilized": "used",
    "utilization": "use",
    "implement": "set up",
    "implementation": "setup",
    "subsequently": "then",
    "consequently": "so",
    "nevertheless": "but",
    "furthermore": "also",
    "approximately": "about",
    "demonstrate": "show",
    "demonstrated": "showed",
    "facilitate": "help",
    "facilitated": "helped",
    "endeavor": "try",
    "endeavored": "tried",
    "comprehend": "understand",
    "comprehension": "understanding",
    "acquisition": "getting",
    "acquire": "get",
    "sufficient": "enough",
    "insufficient": "not enough",
    "numerous": "many",
    "commence": "start",
    "commenced": "started",
    "terminate": "end",
    "terminated": "ended",
    "accomplish": "do",
    "accomplished": "did",
    "ascertain": "find out",
    "constitute": "make up",
    "disseminate": "spread",
    "elucidate": "explain",
    "exacerbate": "worsen",
    "formulate": "create",
    "hypothesize": "guess",
    "inaugurate": "begin",
    "juxtapose": "compare",
    "necessitate": "need",
    "perpetuate": "continue",
    "proliferate": "spread",
    "substantiate": "prove",
    "ubiquitous": "everywhere",
    "unprecedented": "never before seen",
    "ameliorate": "improve",
    "capitulate": "give up",
    "cognizant": "aware",
    "deleterious": "harmful",
    "efficacious": "effective",
    "paradigm": "model",
    "synergy": "teamwork",
    "methodology": "method",
    "parameter": "limit",
    "infrastructure": "structure",
    "photosynthesis": "how plants make food",
    "metamorphosis": "big change",
    "biodiversity": "variety of life",
    "ecosystem": "living system",
    "precipitation": "rain or snow",
    "evaporation": "turning into gas",
    "condensation": "turning into liquid",
    "hypothesis": "educated guess",
    "experiment": "test",
    "observation": "watching closely",
    "conclusion": "final answer",
    "phenomenon": "event",
    "significant": "important",
    "fundamental": "basic",
    "preliminary": "early",
    "comprehensive": "complete",
    "predominant": "main",
    "inevitable": "sure to happen",
    "fluctuate": "change",
    "deteriorate": "get worse",
};

export function simplifyText(input: string): string {
    let result = input;
    for (const [complex, simple] of Object.entries(jargonMap)) {
        const regex = new RegExp(`\\b${complex}\\b`, "gi");
        result = result.replace(regex, (match) => {
            if (match[0] === match[0].toUpperCase()) {
                return simple.charAt(0).toUpperCase() + simple.slice(1);
            }
            return simple;
        });
    }
    return result;
}
